### ISSUE TITLE
Unable cancel in Add Custom Node modal page

### ISSUE THREAD

**Issue by htobenothing** [theQRL/qrl-wallet#111]
1. no response when click cancel button
2. press "Esc" ,the modal disappear. After that click add/edit customer node there is no response
![customernode error](https://user-images.githubusercontent.com/16014993/34285068-b8f8bd90-e711-11e7-9380-535cf154bc52.png)

**Comment by scottdonaldau** [comment]
Hi @htobenothing I've been unable to replicate issue number 1 you've pointed out. On all pages I'm able to click Cancel and it works. I have been able to replicate issue number 2 which I'll investigate a fix for soon.

**Comment by htobenothing** [comment]
1st issue,  Currently I try again in Safari/Chrome browser,   did not come out again, seems ok now. later will use Firefox quantum and IE to test.

**Comment by htobenothing** [comment]
1st issue,  firefox quantum/ microsoft edge  are ok . 

new issue:
for IE 11.125.16299, can not open wallet website. not sure whether need to support IE. 
![ie](https://user-images.githubusercontent.com/16014993/34345449-1c928622-ea2a-11e7-962b-1df7c208d0e5.JPG)

**Comment by scottdonaldau** [comment]
Hey @htobenothing I've not tested too much in IE thus far - though that appears to be indicating a problem loading the web assemblies. If you could log a different issue for that I'll take a look from there. Thanks!

**Comment by scottdonaldau** [comment]
This issue has been resolved in 0df6648
