### ISSUE TITLE
Looking for information

### ISSUE THREAD

**Issue by galations522** [theQRL/qrl-wallet#124]
Is there a chance untill the final release we can get what is to be expected in a screen shot. 
/wallet/wallet.qrl
/wallet/slave.qrl
start_qrl
questionable things. 
Found a transfer in the wallet.qrl but it disappeared after the update
When doing an update the update creates two new accounts instead of holding on to the previous accounts.

Beyond that I am simply waiting on the next release before testing do to debian 9

**Comment by scottdonaldau** [comment]
Hey @galations522 The files you're referencing are related to the QRL Node component, and not the web based wallet found in this repo.

Could you please log this issue in github.com/theQRL/QRL ?
