### ISSUE TITLE
Sending multiple TX to different addresses requires reload of wallet for next TX

### ISSUE THREAD

**Issue by QRLmining** [theQRL/qrl-wallet#148]
When sending multiple transactions you have to reload the wallet, or browse away from the "send" tab, and back, triggering a refresh/sync which takes quite some time.

Is it possible to redirect directly back to a blank "send" form ready to enter new transaction details automatically after successful send? 

Maybe allow multiple transactions to be entered at the same time, with separate details, OTS keys and TX fees to be submitted at the same time from the wallet.

**Comment by scottdonaldau** [comment]
The UX for sending multiple transactions has now been fixed up. Clicking Send/Receive again will prompt different warnings depending on the status of a transaction, or simply reload the send form.
