### ISSUE TITLE
No error if insufficient quanta to pay fee

### ISSUE THREAD

**Issue by baudje** [theQRL/qrl-wallet#152]
if a tx is created but insufficient quanta to pay for the tx fee, the wallet shows the tx is sent to the network and status pending, even though the network has not received/processed the tx. User should know that something went wrong

**Comment by scottdonaldau** [comment]
Thanks @baudje I'll work on this through the coming days.

**Comment by scottdonaldau** [comment]
Form validation has been added so that fee must be set. There is technically no minimum fee - you can send a txn with 0 fee and if a miner adds it to a block, then its verified for free. Miners will of course prioritise txns with fees over those without however.
