### ISSUE TITLE
tx history in wallet limited to <310 tx

### ISSUE THREAD

**Issue by baudje** [theQRL/qrl-wallet#156]
transaction history in the wallet is cut off at around 310 tx. Token creation tx done earlier mean these tokens do not show up in Token Balances tab nor can be selected for a transfer.

**Comment by scottdonaldau** [comment]
Will add pagination to resolve this as is implemented in the explorer.

**Comment by scottdonaldau** [comment]
A patch has been released to resolve this issue. Please let us know if the issue persists. We are going to provide further improvements to pagination at the node gRPC layer in a coming release that will solidify this fix.

**Comment by baudje** [comment]
don't have the number of tx to verify after fork but I trust you have checked 🥇
