### ISSUE TITLE
View hexseed/mnemonic phrase for unlocked wallets

### ISSUE THREAD

**Issue by jplomas** [theQRL/qrl-wallet#174]
As per the title, it should be possible for the user to view the hexseed/mnemonic phrase for unlocked wallets.

UX should ask for confirmation of password for encrypted wallets and limit the time the information is displayed.

Thanks to Discord community member Kurret for this suggestion.

**Comment by scottdonaldau** [comment]
This has been implemented as a modal in https://github.com/theQRL/qrl-wallet/pull/217

You can click a button in the 'Receive' tab to view your mnemonic and hexseed.

There are no time limitations, or password requirement to view these details, though you do have to specifically click a button to bring up the information. As the XMSS object is loaded when you open a wallet, this data is technically accessible by javascript without the requirement of a password to view.

@jplomas Can you please provide feedback on this implementation before it is merged into master.

**Comment by jplomas** [comment]
It works and is important functionality for mainnet release -- let's merge.

In the longer term we should rework the UX -- it is a little counter-intuitive that this information is in the "receive" panel.  A post-mainnet task.

We could also consider recycling the timeout code from block-explorer to automatically lock the wallets after a period of browser inactivity.

**Comment by jplomas** [comment]
Implemented in #217
