### ISSUE TITLE
Alternate hash functions

### ISSUE THREAD

**Issue by surg0r** [theQRL/qrl-wallet#177]
The node natively supports `XMSS` with `SHAKE-128`, `SHAKE-256` and `SHA2-256` cryptographic hash functions at present. The chosen hash function is encoded into the first two bytes of the standard QRL Q-address (or more accurately nibble 0 of byte 0).

Although the explorer properly displays addresses with correct encoding to show the appropriate hash function, in the wallet currently, trying to open a wallet with a hexseed or mnemonic with either `SHAKE-256` or `SHA2-256` encoding instead incorrectly creates an `XMSS/SHAKE-128` tree with a resultant incorrect Q-address.

Thus, it is impossible for a user to open their wallet or see their correct address.

**Comment by scottdonaldau** [comment]
Thanks for reporting this @surg0r 

@jleni is working on a new release of https://github.com/theQRL/qrllib which supports new functionality exposed to web assemblies to restore from an extended seed. This will be implemented shortly after its release on npm.

**Comment by scottdonaldau** [comment]
This was resolved in a61874cc25b45f3c90613ae787695b761e15cf59
