### ISSUE TITLE
Notarisation/data stamping functionality

### ISSUE THREAD

**Issue by surg0r** [theQRL/qrl-wallet#224]
It would be easy to add a tab to the webwallet which constructs and sends a ```message_tx``` containing a ```sha256``` 32 byte hash digest with some simple additional encoding bytes to specify the payload as a notary tx.

The data to be hashed can be drag/dropped into a window or opened with an find file option. The page would then hash the file to generate a unique 32 byte digest. Clicking  a notarize button would then sends the specially crafted ```message_tx``` into the network.

Another part of the page would display existing/previously sent notary tx with date/time/freetext and associated hex hash digest.

The format could be something like:
 ```2 byte notary ID, 1 byte hash function encoding, 5 bytes reserved, 32 byte hash digest, 40 byte utf-8 freetext descriptor```

This functionality requires no changes elsewhere although we could update the explorer to display notary tx by parsing ```message_tx``` 80 byte payloads. This would allow anyone to easily prove something has been hashed in the QRL chain.

An option to download a pdf page with details of the process for posterity may also prove useful. 

The 40 byte freetext descriptor could be optionally encrypted using the wallet key.

**Comment by jplomas** [comment]
Implemented in #243
