### ISSUE TITLE
Sending QRL

### ISSUE THREAD

**Issue by Salekliben** [theQRL/qrl-wallet#252]
I am trying to send my qrl coins to the exchange, but it seems impossible. It says "generating transaction", and it last forever, no transaction. Please tell me what i'm doing wrong?

**Comment by jplomas** [comment]
Does the address you’re trying to send to begin with 0x ?  If so, you’re trying to send Mainnet Quanta to an Ethereum ERC20 address which is impossible: they are completely separate Blockchains.

We should run a validate-qrl-address call on “to” addresses before attempting to sign the transactions in wallet, and have some UI improvements around warning people that it is impossible to send Quanta to an ERC20 address.

**Comment by Salekliben** [comment]
Thanks for quick answer.
That's right! The address begins with 0x. 
So what should I do now? How to transfer coins from WEB wallet to exchange? 
Sorry, but I don't know what this validation means exactly...? I hear it for the first time, I have mined many coins so far, I didn't have this kind of problem.

**Comment by noremac2007** [comment]
No exchange supports the real coin yet.. You can't offload until someone picks it up
