### ISSUE TITLE
Transaction Generation Failed Error: Internal server error [500]

### ISSUE THREAD

**Issue by jph108** [theQRL/qrl-wallet#255]
Hello,

I have created a couple of mainnet addresses using wallet.theqrl.org, and tried to send some mainnet QRL from one to the other. When I open the wallet, the Transaction History section on the right never loads, the spinner just keeps spinning. If I try to go ahead and send a transaction, I get "Transaction Generation Failed Error: Internal server error [500]".

Using the latest version of Chrome on Mac OS High Sierra. 

With Best Regards,
Josh

**Comment by scottdonaldau** [comment]
Hey @jph108 

At the top right of the wallet, please ensure the dropdown has 'Mainnet' selected. Let me know if this resolves your issue.

Cheers,
Scott

**Comment by jph108** [comment]
Sure. At the bottom of the console dump, the Uncaught TypeError occurred after I clicked "Confirm" while trying to send.

![error](https://user-images.githubusercontent.com/1222784/43385079-cceba1d4-93ad-11e8-8c1a-b836ef284df3.png)

![console dump](https://user-images.githubusercontent.com/1222784/43384873-4c6f7c56-93ad-11e8-8929-bd112162563f.png)

**Comment by jph108** [comment]
Just tried it again with all extensions disabled, and got the same error.

**Comment by scottdonaldau** [comment]
@jph108 Are you trying to send a transaction that has more Quanta than is available in your wallet? I can see the following error a few times recently in the wallet nodes logs.

```
2018-07-30 08:08:25,018|1.0.0|synced  |Thread-2   | DEBUG : [PublicAPI] TransferCoins
2018-07-30 08:08:25,019|1.0.0|synced  |Thread-2   | INFO : Not enough funds in the source address
```

I don't have more detailed information relevant to your specific transaction - if you wanted to get in touch privately without revealing specific transaction details on Github, feel free to ping me on Discord.

**Comment by EGartin** [comment]
I'm having a similar issue, although looking at the error logs I think it may have to do with NordVPN.  I'm going to try the transaction again after disconnecting.
[wallet.theqrl.org-1545972248851.log](https://github.com/theQRL/qrl-wallet/files/2713993/wallet.theqrl.org-1545972248851.log)

**Comment by EGartin** [comment]
Confirmed, issue was with NordVPN

**Comment by scottdonaldau** [comment]
This has been resolved - friendly error messages now show in wallet UI.
