### ISSUE TITLE
I can not transfer to the Bittrex wallet.

### ISSUE THREAD

**Issue by tipo7026** [theQRL/qrl-wallet#256]
I can not transfer to the Bittrex wallet. Constantly lit the inscription "JAST A MOMENT" and nothing happens. What could be the problem?
![qrl](https://user-images.githubusercontent.com/42063987/43639202-1ca9bdea-9724-11e8-9aa6-eab4c2475d2d.jpg)

**Comment by jplomas** [comment]
This is a duplicate of #252

Bittrex are currently using ERC20 addresses which are on the Ethereum blockchain.

You cannot send QRL from a Q-address to an Ethereum 0x-address.

**Comment by tipo7026** [comment]
And how, then, to bring QRL to the stock exchange?

**Comment by noremac2007** [comment]
You can't until some exchange implements new code and accepts the new addresses

**Comment by tipo7026** [comment]
Why such a coin?

**Comment by tipo7026** [comment]
Why such a coin is needed?

**Comment by tipo7026** [comment]
What is the meaning of this coin?

**Comment by jplomas** [comment]
The case for a Quantum Resistant Ledger is eloquently made in our Whitepaper: 
https://github.com/theQRL/Whitepaper/blob/master/QRL_whitepaper.pdf
