### ISSUE TITLE
Coins were not received

### ISSUE THREAD

**Issue by EraLno** [theQRL/qrl-wallet#262]
A few days do not come coins with http: //www.qrlpool.com
https://ibb.co/h2Qft9
https://ibb.co/nhjvRU

In the wallet you can see that there were no transactions

Q010500a0dd885f7b6451702b7ac814f874dfdd018caa1e9bec2b2ae67d624740087b53786c9194

**Comment by jplomas** [comment]
In your screenshot you have “Testnet” selected for your wallet in the upper right corner.

Change this to Mainnet.

The address quoted has 32 transactions in the block explorer.

**Comment by EraLno** [comment]
Thank you, sorry for my inattention
