### ISSUE TITLE
[SOLVED] Mac OS 10.12.6 - Error: Cannot find module grpc_module.node

### ISSUE THREAD

**Issue by ubidefeo** [theQRL/qrl-wallet#27]
If anyone bumps into this Error after launching with `meteor` it may need some rebuilding.

according to setup instructions
```
git clone https://github.com/theQRL/qrl-wallet.git
cd qrl-wallet
meteor npm install
meteor npm install --save meteor-babel-helpers
```
when launching with `meteor` you may run into this issue.

quit `CTRL+C` and run 
```
meteor npm rebuild
```

It worked for me, have the web app running :)
(maybe this note could be added to the setup info)

**Comment by scottdonaldau** [comment]
Thanks @ubidefeo I'll aim to have it fixed up this week.

**Comment by scottdonaldau** [comment]
This can be solved by a clean git pull of the repo, and replace `meteor npm install` with `meteor npm install --unsafe-perm`

See https://github.com/grpc/grpc/issues/6435 for more info on the issue.

**Comment by scottdonaldau** [comment]
I've updated the documentation to reflect this in #30
