### ISSUE TITLE
Coinbase reward not calculated correctly

### ISSUE THREAD

**Issue by randomshinichi** [theQRL/qrl-wallet#272]
![localhost_4000_transfer](https://user-images.githubusercontent.com/9956122/45107343-91abae80-b139-11e8-8234-9329956714a0.png)
On master commit. I'd take a screenshot of wallet.theqrl.org but official testnet nodes are down

**Comment by scottdonaldau** [comment]
Good spot @randomshinichi - I've fixed this up and will be merged with latest release that contains other improvements.
