### ISSUE TITLE
Unencrypted bech32 & PK 

### ISSUE THREAD

**Issue by 0xFF0** [theQRL/qrl-wallet#279]
The "Save Secure Wallet File" does not encrypt the bech32 address in the json wallet. PK data is also stored unencrypted.

**Comment by surg0r** [comment]
Requires an urgent fix as this leaks address and public key data unexpectedly. Well spotted.

**Comment by scottdonaldau** [comment]
Fix has been merged to devnet branch, will make its way to production in next release.
