### ISSUE TITLE
Transaction Generation Failed [500] when sending more than total balance

### ISSUE THREAD

**Issue by jackalyst** [theQRL/qrl-wallet#282]
When sending a transaction for an amount greater than the users total balance (usually by sending the full balance and not subtracting the network fee), the user is treated to a confusing Server Error [500] page rather than one that's useful.

Recommend having either a more useful error prompt or page.

**Comment by scottdonaldau** [comment]
Duplicate of https://github.com/theQRL/qrl-wallet/issues/255 - Will aim to fix before next release
