### ISSUE TITLE
ImportDeclaration should appear when the mode is ES6 and in the module context

### ISSUE THREAD

**Issue by DaniellMesquita** [theQRL/qrl-wallet#368]
Not all apps throws these errors when auditing.
Fixing it is needed for parsing.

Error parsing /1/Apps/qrl-wallet/server/main.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/qrl-wallet/client/main.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/qrl-wallet/imports/startup/both/index.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/qrl-wallet/imports/startup/client/functions.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/qrl-wallet/imports/startup/client/index.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/qrl-wallet/imports/startup/client/routes.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/qrl-wallet/imports/startup/server/index.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/qrl-wallet/imports/ui/mobile/mobile.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/qrl-wallet/imports/ui/layouts/body/body.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/qrl-wallet/imports/ui/pages/close/close.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/qrl-wallet/imports/ui/pages/not-found/not-found.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/qrl-wallet/imports/ui/pages/create/address.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/qrl-wallet/imports/ui/pages/create/create.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/qrl-wallet/imports/ui/pages/open/open.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/qrl-wallet/imports/ui/pages/tokens/tokenCreate.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/qrl-wallet/imports/ui/pages/tokens/tokenCreateConfirm.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/qrl-wallet/imports/ui/pages/tokens/tokenCreateResult.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/qrl-wallet/imports/ui/pages/transfer/reload.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/qrl-wallet/imports/ui/pages/transfer/transfer.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/qrl-wallet/imports/ui/pages/verify/tx.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/qrl-wallet/imports/ui/pages/verify/verify.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/qrl-wallet/imports/ui/pages/tools/tools.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/qrl-wallet/imports/ui/pages/tools/keybase/keybaseConfirm.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/qrl-wallet/imports/ui/pages/tools/keybase/keybaseCreate.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/qrl-wallet/imports/ui/pages/tools/keybase/keybaseResult.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/qrl-wallet/imports/ui/pages/tools/notarise/confirm.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/qrl-wallet/imports/ui/pages/tools/notarise/result.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/qrl-wallet/imports/ui/pages/tools/notarise/start.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/qrl-wallet/imports/ui/pages/tools/github/githubConfirm.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/qrl-wallet/imports/ui/pages/tools/github/githubCreate.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/qrl-wallet/imports/ui/pages/tools/github/githubResult.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/qrl-wallet/imports/ui/pages/tools/message/messageConfirm.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/qrl-wallet/imports/ui/pages/tools/message/messageCreate.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/qrl-wallet/imports/ui/pages/tools/message/messageResult.js - ImportDeclaration should appear when the mode is ES6 and in the module context.
Error parsing /1/Apps/qrl-wallet/imports/ui/pages/tools/xmssindex/update.js - ImportDeclaration should appear when the mode is ES6 and in the module context.

**Comment by DaniellMesquita** [comment]
Reference: https://github.com/theQRL/qrl-wallet/issues/367

**Comment by jplomas** [comment]
These are non-fatal linting errors when using a 3rd party security auditing tool.

eslint works correctly and as intended within qrl-wallet repo so you may wish to investigate if this is an issue with your setup (by ensuring the applications lints, builds and runs correctly) prior to using the 3rd party security auditing tool or indeed an error in the tool itself.

**Comment by DaniellMesquita** [comment]
@jplomas hi. I've used electronegativity, and not all apps throws these lint errors. How other apps doesn't?

**Comment by DaniellMesquita** [comment]
Probably other lints doesn't understands about NodeJS/Electron's require/import.
electronegativity is focused on Electron apps.

**Comment by jplomas** [comment]
At a guess it is linting based on electronegativity's eslint config file (https://github.com/doyensec/electronegativity/blob/master/.eslintrc.json) rather than qrl-wallet's

**Comment by DaniellMesquita** [comment]
Probably it is a misconfiguration on electronegativity?
