### ISSUE TITLE
Wallet v 1.5.0 crashes to whitescreen on launch

### ISSUE THREAD

**Issue by ChristianOConnor** [theQRL/qrl-wallet#427]
I have Catalina 10.15.4 on a 2017 2 thunderbolt 3 port MacBook Pro. Just as the title says the app won't even launch. It just gives the outline of the windows with a white interior.

**Comment by jplomas** [comment]
Hi @ChristianOConnor 

The release version was tested on Catalina and High Sierra prior to release.  Are you running offline or with internet connectivity?

A command line dump would be helpful to see where things stall for you.  If you open a terminal prompt and run:
`/Applications/QRLWallet.app/Contents/MacOS/QRLWallet`
you should get terminal output which will help us pinpoint any issues.

**Comment by ChristianOConnor** [comment]
I uninstalled the wallet before I could recreate the steps that caused the error and then I got this message when I re-downloaded the disk image and tried to open it.
<img width="484" alt="Screen Shot 2020-06-07 at 6 35 12 PM" src="https://user-images.githubusercontent.com/47836708/83981657-cee43800-a8ed-11ea-8f3e-2a51fa52d0fc.png">

**Comment by ChristianOConnor** [comment]
Nevermind, I was able to install it. Here is what my terminal says:

`~ % /Applications/QRLWallet.app/Contents/MacOS/QRLWallet
INFO  electrify:index:  initializing
INFO  electrify:plugins:  use  nodejs
INFO  electrify:plugins:  use  socket
INFO  electrify:index:  start
INFO  electrify:plugins:  start
INFO  electrify:plugins:socket:  starting socket
SockJS v0.3.19 bound to "/electrify"
INFO  electrify:index:  socket listening at 11235
INFO  electrify:plugins:nodejs:  starting meteor...
QRL Wallet Starting - Version: 1.5.0
Attempting to create gRPC connections to network: Mainnet ...
Attempting to create gRPC connection to network: Mainnet, node: mainnet-1 (mainnet-1.automated.theqrl.org:19009) ...
Establishing new connection to mainnet-1.automated.theqrl.org:19009
Attempting to create gRPC connection to network: Mainnet, node: mainnet-3 (mainnet-3.automated.theqrl.org:19009) ...
Establishing new connection to mainnet-3.automated.theqrl.org:19009
Attempting to create gRPC connections to network: Testnet ...
Attempting to create gRPC connection to network: Testnet, node: testnet-1 (testnet-1.automated.theqrl.org:19009) ...
Establishing new connection to testnet-1.automated.theqrl.org:19009
Attempting to create gRPC connection to network: Testnet, node: testnet-2 (testnet-2.automated.theqrl.org:19009) ...
Establishing new connection to testnet-2.automated.theqrl.org:19009
Attempting to create gRPC connection to network: Testnet, node: testnet-4 (testnet-4.automated.theqrl.org:19009) ...
Establishing new connection to testnet-4.automated.theqrl.org:19009
Attempting to create gRPC connections to network: Localhost (Desktop App Only) ...
Attempting to create gRPC connection to network: Localhost (Desktop App Only), node: localhost (localhost:19009) ...
Establishing new connection to localhost:19009
(node:1343) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
Error fetching qrl.proto from localhost:19009
Failed to connect to node localhost:19009
**ERROR/connection**  [Timestamp: Sun, 07 Jun 2020 22:39:36 GMT] Error: 14 UNAVAILABLE: failed to connect to all addresses
Failed to connect to node localhost:19009
Cannot verify QRL node version on: mainnet-1.automated.theqrl.org:19009 - Version: 2.0.1+0.gf457b3a.dirty python
**ERROR/connect** [Timestamp: Sun, 07 Jun 2020 22:39:36 GMT] null
Failed to connect to node mainnet-1.automated.theqrl.org:19009
**ERROR/connection**  [Timestamp: Sun, 07 Jun 2020 22:39:36 GMT] Error: [Sun, 07 Jun 2020 22:39:36 GMT] Cannot verify QRL node version on: mainnet-1.automated.theqrl.org:19009 - Version: 2.0.1+0.gf457b3a.dirty python (null) [500]
Failed to connect to node mainnet-1.automated.theqrl.org:19009
proto: checking that calc of b24a5c41468610914da57ac92f3cc2f74d89575f2626d5968f84ca211f55410c = expected b24a5c41468610914da57ac92f3cc2f74d89575f2626d5968f84ca211f55410c
object: checking that calc of f6b06eac25bd5740fe6877d5e604429e6aadd93dee668e7412051decbf34add2 = expected f6b06eac25bd5740fe6877d5e604429e6aadd93dee668e7412051decbf34add2
qrlClient loaded for mainnet-1.automated.theqrl.org:19009
Connected to mainnet-1.automated.theqrl.org:19009
Cannot verify QRL node version on: testnet-1.automated.theqrl.org:19009 - Version: 0.2.0 python
**ERROR/connect** [Timestamp: Sun, 07 Jun 2020 22:39:36 GMT] null
Failed to connect to node testnet-1.automated.theqrl.org:19009
**ERROR/connection**  [Timestamp: Sun, 07 Jun 2020 22:39:36 GMT] Error: [Sun, 07 Jun 2020 22:39:36 GMT] Cannot verify QRL node version on: testnet-1.automated.theqrl.org:19009 - Version: 0.2.0 python (null) [500]
Failed to connect to node testnet-1.automated.theqrl.org:19009
Cannot verify QRL node version on: mainnet-3.automated.theqrl.org:19009 - Version: 2.0.1+0.gf457b3a.dirty python
**ERROR/connect** [Timestamp: Sun, 07 Jun 2020 22:39:36 GMT] null
Failed to connect to node mainnet-3.automated.theqrl.org:19009
**ERROR/connection**  [Timestamp: Sun, 07 Jun 2020 22:39:36 GMT] Error: [Sun, 07 Jun 2020 22:39:36 GMT] Cannot verify QRL node version on: mainnet-3.automated.theqrl.org:19009 - Version: 2.0.1+0.gf457b3a.dirty python (null) [500]
Failed to connect to node mainnet-3.automated.theqrl.org:19009
Cannot verify QRL node version on: testnet-4.automated.theqrl.org:19009 - Version: 0.2.0 python
**ERROR/connect** [Timestamp: Sun, 07 Jun 2020 22:39:36 GMT] null
Failed to connect to node testnet-4.automated.theqrl.org:19009
**ERROR/connection**  [Timestamp: Sun, 07 Jun 2020 22:39:36 GMT] Error: [Sun, 07 Jun 2020 22:39:36 GMT] Cannot verify QRL node version on: testnet-4.automated.theqrl.org:19009 - Version: 0.2.0 python (null) [500]
Failed to connect to node testnet-4.automated.theqrl.org:19009
Cannot verify QRL node version on: testnet-2.automated.theqrl.org:19009 - Version: 0.2.0 python
**ERROR/connect** [Timestamp: Sun, 07 Jun 2020 22:39:36 GMT] null
Failed to connect to node testnet-2.automated.theqrl.org:19009
**ERROR/connection**  [Timestamp: Sun, 07 Jun 2020 22:39:36 GMT] Error: [Sun, 07 Jun 2020 22:39:36 GMT] Cannot verify QRL node version on: testnet-2.automated.theqrl.org:19009 - Version: 0.2.0 python (null) [500]
Failed to connect to node testnet-2.automated.theqrl.org:19009
proto: checking that calc of ab168a46875c6dc41000080804c858b9039aae977dfd5503d9eb234ece4e3510 = expected ab168a46875c6dc41000080804c858b9039aae977dfd5503d9eb234ece4e3510
object: checking that calc of 0ead495c340fd331b28e325166ffe162a0f7cc3929b559f47d3691aeb0541bae = expected 0ead495c340fd331b28e325166ffe162a0f7cc3929b559f47d3691aeb0541bae
qrlClient loaded for testnet-1.automated.theqrl.org:19009
Connected to testnet-1.automated.theqrl.org:19009
proto: checking that calc of ab168a46875c6dc41000080804c858b9039aae977dfd5503d9eb234ece4e3510 = expected ab168a46875c6dc41000080804c858b9039aae977dfd5503d9eb234ece4e3510
object: checking that calc of 0ead495c340fd331b28e325166ffe162a0f7cc3929b559f47d3691aeb0541bae = expected 0ead495c340fd331b28e325166ffe162a0f7cc3929b559f47d3691aeb0541bae
qrlClient loaded for testnet-4.automated.theqrl.org:19009
Connected to testnet-4.automated.theqrl.org:19009
proto: checking that calc of ab168a46875c6dc41000080804c858b9039aae977dfd5503d9eb234ece4e3510 = expected ab168a46875c6dc41000080804c858b9039aae977dfd5503d9eb234ece4e3510
object: checking that calc of 0ead495c340fd331b28e325166ffe162a0f7cc3929b559f47d3691aeb0541bae = expected 0ead495c340fd331b28e325166ffe162a0f7cc3929b559f47d3691aeb0541bae
qrlClient loaded for testnet-2.automated.theqrl.org:19009
Connected to testnet-2.automated.theqrl.org:19009
proto: checking that calc of b24a5c41468610914da57ac92f3cc2f74d89575f2626d5968f84ca211f55410c = expected b24a5c41468610914da57ac92f3cc2f74d89575f2626d5968f84ca211f55410c
object: checking that calc of f6b06eac25bd5740fe6877d5e604429e6aadd93dee668e7412051decbf34add2 = expected f6b06eac25bd5740fe6877d5e604429e6aadd93dee668e7412051decbf34add2
qrlClient loaded for mainnet-3.automated.theqrl.org:19009
Connected to mainnet-3.automated.theqrl.org:19009
Connected to mainnet-1.automated.theqrl.org:19009
Connected to testnet-1.automated.theqrl.org:19009
Connected to testnet-4.automated.theqrl.org:19009
Connected to mainnet-3.automated.theqrl.org:19009
Connected to testnet-2.automated.theqrl.org:19009
INFO  electrify:app:  terminating app
INFO  electrify:plugins:  stop
electrify stop done`



And this is what the wallet looks like:
<img width="1412" alt="Screen Shot 2020-06-07 at 6 39 52 PM" src="https://user-images.githubusercontent.com/47836708/83981730-811bff80-a8ee-11ea-9d18-914f951f8fdf.png">

**Comment by jplomas** [comment]
Thanks for helping to improve the wallet.

Unfortunately I can't replicate this on Catalina 10.15.5.

Did you have a previous version of the wallet installed?  If so, using [AppCleaner](https://freemacsoft.net/appcleaner/) to remove the application and all files/folders _may_ be helpful.

Does the splash screen with the QRL logo and "Loading..." appear before this white page opens?

Finally, are you running any blocking tools that could interfere with network traffic?

**Comment by ChristianOConnor** [comment]
Tried Uninstalling it with AppCleaner, still nothing. I have Little Snitch but I keep it set it to "Silent Mode - Allow Connections" where it let's all traffic to and from my computer through. I do get that small window with a QRL logo on it for a second while the wallet starts up, but then it's straight to the white screen.

I have to click through all these screens when I run it for the first time. Maybe it could have something to do with that?
<img width="578" alt="Screen Shot 2020-06-10 at 10 35 26 PM" src="https://user-images.githubusercontent.com/47836708/84338958-699d7a80-ab6b-11ea-90cf-3388424fc72a.png">
<img width="532" alt="Screen Shot 2020-06-10 at 10 34 40 PM" src="https://user-images.githubusercontent.com/47836708/84338962-6a361100-ab6b-11ea-84b7-e5718f0200be.png">
<img width="581" alt="Screen Shot 2020-06-10 at 10 35 52 PM" src="https://user-images.githubusercontent.com/47836708/84338967-6bffd480-ab6b-11ea-84e8-74b1b9179983.png">

**Comment by jplomas** [comment]
The warnings are usual for non-Apple signed code.

I've been able to reproduce a white screen by manually mangling the code, so I wonder if you have an environment variable set somewhere that is causing problems with the instance of node that runs when the app is started.  To help further troubleshooting could you try the following?

In:
 ``/Applications/QRLWallet.app/Contents/Resources/app/index.js``

Below
``// Electrify Start``
``  electrify.start(function(meteor_root_url) {``
can you add:
  ``console.log('passed: ' + meteor_root_url)``

Then run from command line and paste here the line that starts with ``passed:``

Thanks again for your help debugging this.

**Comment by ChristianOConnor** [comment]
Okay I added the line in index.js. Here is the output.

`~ %  /Applications/QRLWallet.app/Contents/MacOS/QRLWallet
INFO  electrify:index:  initializing
INFO  electrify:plugins:  use  nodejs
INFO  electrify:plugins:  use  socket
INFO  electrify:index:  start
INFO  electrify:plugins:  start
INFO  electrify:plugins:socket:  starting socket
SockJS v0.3.19 bound to "/electrify"
INFO  electrify:index:  socket listening at 11235
INFO  electrify:plugins:nodejs:  starting meteor...
QRL Wallet Starting - Version: 1.5.0
Attempting to create gRPC connections to network: Mainnet ...
Attempting to create gRPC connection to network: Mainnet, node: mainnet-1 (mainnet-1.automated.theqrl.org:19009) ...
Establishing new connection to mainnet-1.automated.theqrl.org:19009
Attempting to create gRPC connection to network: Mainnet, node: mainnet-3 (mainnet-3.automated.theqrl.org:19009) ...
Establishing new connection to mainnet-3.automated.theqrl.org:19009
Attempting to create gRPC connections to network: Testnet ...
Attempting to create gRPC connection to network: Testnet, node: testnet-1 (testnet-1.automated.theqrl.org:19009) ...
Establishing new connection to testnet-1.automated.theqrl.org:19009
Attempting to create gRPC connection to network: Testnet, node: testnet-2 (testnet-2.automated.theqrl.org:19009) ...
Establishing new connection to testnet-2.automated.theqrl.org:19009
Attempting to create gRPC connection to network: Testnet, node: testnet-4 (testnet-4.automated.theqrl.org:19009) ...
Establishing new connection to testnet-4.automated.theqrl.org:19009
Attempting to create gRPC connections to network: Localhost (Desktop App Only) ...
Attempting to create gRPC connection to network: Localhost (Desktop App Only), node: localhost (localhost:19009) ...
Establishing new connection to localhost:19009
(node:1340) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
passed: http://127.0.0.1:11236
Error fetching qrl.proto from localhost:19009
Failed to connect to node localhost:19009
**ERROR/connection**  [Timestamp: Thu, 11 Jun 2020 21:12:00 GMT] Error: 14 UNAVAILABLE: failed to connect to all addresses
Failed to connect to node localhost:19009
Cannot verify QRL node version on: mainnet-1.automated.theqrl.org:19009 - Version: 2.0.1+0.gf457b3a.dirty python
**ERROR/connect** [Timestamp: Thu, 11 Jun 2020 21:12:00 GMT] null
Failed to connect to node mainnet-1.automated.theqrl.org:19009
**ERROR/connection**  [Timestamp: Thu, 11 Jun 2020 21:12:00 GMT] Error: [Thu, 11 Jun 2020 21:12:00 GMT] Cannot verify QRL node version on: mainnet-1.automated.theqrl.org:19009 - Version: 2.0.1+0.gf457b3a.dirty python (null) [500]
Failed to connect to node mainnet-1.automated.theqrl.org:19009
proto: checking that calc of b24a5c41468610914da57ac92f3cc2f74d89575f2626d5968f84ca211f55410c = expected b24a5c41468610914da57ac92f3cc2f74d89575f2626d5968f84ca211f55410c
object: checking that calc of f6b06eac25bd5740fe6877d5e604429e6aadd93dee668e7412051decbf34add2 = expected f6b06eac25bd5740fe6877d5e604429e6aadd93dee668e7412051decbf34add2
qrlClient loaded for mainnet-1.automated.theqrl.org:19009
Connected to mainnet-1.automated.theqrl.org:19009
Cannot verify QRL node version on: mainnet-3.automated.theqrl.org:19009 - Version: 2.0.1+0.gf457b3a.dirty python
**ERROR/connect** [Timestamp: Thu, 11 Jun 2020 21:12:01 GMT] null
Failed to connect to node mainnet-3.automated.theqrl.org:19009
**ERROR/connection**  [Timestamp: Thu, 11 Jun 2020 21:12:01 GMT] Error: [Thu, 11 Jun 2020 21:12:01 GMT] Cannot verify QRL node version on: mainnet-3.automated.theqrl.org:19009 - Version: 2.0.1+0.gf457b3a.dirty python (null) [500]
Failed to connect to node mainnet-3.automated.theqrl.org:19009
Cannot verify QRL node version on: testnet-4.automated.theqrl.org:19009 - Version: 0.2.0 python
**ERROR/connect** [Timestamp: Thu, 11 Jun 2020 21:12:01 GMT] null
Failed to connect to node testnet-4.automated.theqrl.org:19009
**ERROR/connection**  [Timestamp: Thu, 11 Jun 2020 21:12:01 GMT] Error: [Thu, 11 Jun 2020 21:12:01 GMT] Cannot verify QRL node version on: testnet-4.automated.theqrl.org:19009 - Version: 0.2.0 python (null) [500]
Failed to connect to node testnet-4.automated.theqrl.org:19009
Cannot verify QRL node version on: testnet-2.automated.theqrl.org:19009 - Version: 0.2.0 python
**ERROR/connect** [Timestamp: Thu, 11 Jun 2020 21:12:01 GMT] null
Failed to connect to node testnet-2.automated.theqrl.org:19009
**ERROR/connection**  [Timestamp: Thu, 11 Jun 2020 21:12:01 GMT] Error: [Thu, 11 Jun 2020 21:12:01 GMT] Cannot verify QRL node version on: testnet-2.automated.theqrl.org:19009 - Version: 0.2.0 python (null) [500]
Failed to connect to node testnet-2.automated.theqrl.org:19009
Cannot verify QRL node version on: testnet-1.automated.theqrl.org:19009 - Version: 0.2.0 python
**ERROR/connect** [Timestamp: Thu, 11 Jun 2020 21:12:01 GMT] null
Failed to connect to node testnet-1.automated.theqrl.org:19009
**ERROR/connection**  [Timestamp: Thu, 11 Jun 2020 21:12:01 GMT] Error: [Thu, 11 Jun 2020 21:12:01 GMT] Cannot verify QRL node version on: testnet-1.automated.theqrl.org:19009 - Version: 0.2.0 python (null) [500]
Failed to connect to node testnet-1.automated.theqrl.org:19009
proto: checking that calc of b24a5c41468610914da57ac92f3cc2f74d89575f2626d5968f84ca211f55410c = expected b24a5c41468610914da57ac92f3cc2f74d89575f2626d5968f84ca211f55410c
object: checking that calc of f6b06eac25bd5740fe6877d5e604429e6aadd93dee668e7412051decbf34add2 = expected f6b06eac25bd5740fe6877d5e604429e6aadd93dee668e7412051decbf34add2
qrlClient loaded for mainnet-3.automated.theqrl.org:19009
Connected to mainnet-3.automated.theqrl.org:19009
proto: checking that calc of ab168a46875c6dc41000080804c858b9039aae977dfd5503d9eb234ece4e3510 = expected ab168a46875c6dc41000080804c858b9039aae977dfd5503d9eb234ece4e3510
object: checking that calc of 0ead495c340fd331b28e325166ffe162a0f7cc3929b559f47d3691aeb0541bae = expected 0ead495c340fd331b28e325166ffe162a0f7cc3929b559f47d3691aeb0541bae
qrlClient loaded for testnet-4.automated.theqrl.org:19009
Connected to testnet-4.automated.theqrl.org:19009
proto: checking that calc of ab168a46875c6dc41000080804c858b9039aae977dfd5503d9eb234ece4e3510 = expected ab168a46875c6dc41000080804c858b9039aae977dfd5503d9eb234ece4e3510
object: checking that calc of 0ead495c340fd331b28e325166ffe162a0f7cc3929b559f47d3691aeb0541bae = expected 0ead495c340fd331b28e325166ffe162a0f7cc3929b559f47d3691aeb0541bae
qrlClient loaded for testnet-2.automated.theqrl.org:19009
Connected to testnet-2.automated.theqrl.org:19009
proto: checking that calc of ab168a46875c6dc41000080804c858b9039aae977dfd5503d9eb234ece4e3510 = expected ab168a46875c6dc41000080804c858b9039aae977dfd5503d9eb234ece4e3510
object: checking that calc of 0ead495c340fd331b28e325166ffe162a0f7cc3929b559f47d3691aeb0541bae = expected 0ead495c340fd331b28e325166ffe162a0f7cc3929b559f47d3691aeb0541bae
qrlClient loaded for testnet-1.automated.theqrl.org:19009
Connected to testnet-1.automated.theqrl.org:19009
Connected to mainnet-1.automated.theqrl.org:19009
Connected to testnet-4.automated.theqrl.org:19009
Connected to testnet-2.automated.theqrl.org:19009
Connected to mainnet-3.automated.theqrl.org:19009
Connected to testnet-1.automated.theqrl.org:19009
INFO  electrify:app:  terminating app
INFO  electrify:plugins:  stop
electrify stop done`

**Comment by jplomas** [comment]
Thank you.  With the wallet running, can you open the URL after 'passed' (e.g. in output above ``http://127.0.0.1:11236``) in Chrome or another web browser and let us know the results and any console errors.

**Comment by ChristianOConnor** [comment]
Huh.... that's weird the wallet works in the web browser! Here's what it says in the web console (I used Firefox by the way).

`Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). contentscript.js:1:380015
The resource from “https://fonts.googleapis.com/css?family=Helvetica:400,700,400italic,700italic&subset=latin” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
127.0.0.1:11236
qrl-wallet -  1.5.0 bd917b59da11644630a0d9ef2e0dc1e6a532985f.js:153:508439
Work with us! jobs@theqrl.org bd917b59da11644630a0d9ef2e0dc1e6a532985f.js:153:508483
Found a security bug? security@theqrl.org bd917b59da11644630a0d9ef2e0dc1e6a532985f.js:153:508528
Found a problem? https://github.com/theQRL/qrl-wallet/issues bd917b59da11644630a0d9ef2e0dc1e6a532985f.js:153:508585
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). bd917b59da11644630a0d9ef2e0dc1e6a532985f.js:85:40013
Connecting to network:  Mainnet bd917b59da11644630a0d9ef2e0dc1e6a532985f.js:153:462392
Web Assembly Supported:  true bd917b59da11644630a0d9ef2e0dc1e6a532985f.js:153:463343
Connection to network is healthy:  mainnet bd917b59da11644630a0d9ef2e0dc1e6a532985f.js:153:462522`

**Comment by jplomas** [comment]
Thanks @ChristianOConnor - I think that effectively pinpoints the issue to a problem with your setup somewhere outside of the wallet.

Given you use Little Snitch, options are:
1. Stopping the Network Filter via the menubar
2. Backup the configuration then completely remove/uninstall the software

If this makes the wallet work, delving deeper into the configuration that has been causing an issue could help others.

I'll leave this issue open for now, but I'm fairly convinced this is not an issue with the wallet package.

Do let us know how you get on!
