### ISSUE TITLE
Open wallet from json file.

### ISSUE THREAD

**Issue by scottdonaldau** [theQRL/qrl-wallet#47]

**Comment by kolanich77** [comment]
Hello. Downloaded the wallet, but can not open it. Only 417 bytes. What do I do? Thanks in advance.

**Comment by scottdonaldau** [comment]
Hey @kolanich77 That's about how big a wallet.json file is.

If you want to view it, just open it in a normal text editor (notepad, vim, sublime, nano etc).

Here's an example:

[{"address":"Q2487b53982a17c051dfbdaa18de3e2f2cfc6ef32c1abff21f387def43a89aeb157d64109","hexseed":"0be06d00f6457e5267c78cdcedf0de8a583d57cd56c92bc3182644cc6c334c3cab1539da905d1278e626e836b03917fb","mnemonic":"ashore along absent halt libya cereal shrug soak union aunt menu lunar friend stay singer rural blew hall slump sent falcon slam bench pact moth spat lad grown tower holder deeply lion","index":0}]

**Comment by scottdonaldau** [comment]
Open from json has been implemented in latest release on wallet.theqrl.org.
