### ISSUE TITLE
Can I cryptomine while my wallet is closed?

### ISSUE THREAD

**Issue by Joe23232** [theQRL/qrl-wallet#488]
Hi, so with my online wallet, say if I have my browser closed, would I still be able to mine? (sorry I am a noob to mining)?

**Comment by jplomas** [comment]
This is wallet software for interacting with public and private nodes.  It is nodes that can undertake mining.

Docs at https://docs.theqrl.org might help you out, or the QRL Discord is packed with friendly and knowledgeable people.

**Comment by Joe23232** [comment]
@jplomas  Hi, can I have the Discord link please?

**Comment by jplomas** [comment]
@Joe23232 https://discord.gg/jBT6BEp

**Comment by Joe23232** [comment]
Thanks man
