### ISSUE TITLE
Ledger not available in Open Wallet 

### ISSUE THREAD

**Issue by dc53223** [theQRL/qrl-wallet#524]
I made sure to connect, unlock, and have the QRL app open on my device, but the only options available to open wallet are mnemonic phrase, hexseed, and wallet file. I tried on the web wallet as well as the desktop wallet on WIndows 11. 

I have Ledger Nano S Plus

**Comment by jplomas** [comment]
Please ensure you are running v1.8.1 of the desktop wallet on Windows 11 (the Ledger option is not available on the web wallet) as support for Windows 11 was added in this version.  If you are using certain scaled display fonts the option may not be visible in the drop down menu - try pressing the 'down' cursor key with the dropdown option to scroll through the options if you already have v1.8.1 installed.

**Comment by dc53223** [comment]
Thank you! I accidentally had an older version.
