### ISSUE TITLE
created QRL wallet 4/20/2021 and now cannot open with either Hexseed or Mneumonic Phrase

### ISSUE THREAD

**Issue by JTolstad** [theQRL/qrl-wallet#530]
Please tell me how to open this wallet I created 2 years ago. I do not remember how many, if any, QRL I have in the wallet.

**Comment by Robyer** [comment]
I recommend you to join official discord channel at https://theqrl.org/discord to get faster help from team and community. Just don't share your seed or anything with anyone, make sure you have it save and backed up. 

Anyway, download latest version of wallet as there had been updates on the blockchain which requires new version. So try it again with freshly installed latest version, maybe it will work.

**Comment by jplomas** [comment]
> Please tell me how to open this wallet I created 2 years ago. I do not remember how many, if any, QRL I have in the wallet.
> 
> 

The quickest way to check your hexseed/mnemonic is via the web wallet deployment at https://wallet.theqrl.org

Watch out for white space if you are copy & pasting from somewhere.

If you have the associated QRL address you can check its mainnet balance at https://explorer.theqrl.org

As noted above, community support is available on Discord and there is also support@theqrl.org for signposting help but as there does not appear to be a code problem I’m closing this issue: feel free to re-open if this is not the case.
